### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by Devansu-Yadav** [Ninja-Developers/phantombucket#5]
## Project Title
9x9 TicTacToe Game

## Description
A fun and easy to play TicTacToe game but with a little twist that it is a 9x9 Grid instead of a 3x3 Grid. 

## Github repo link
[https://github.com/Devansu-Yadav/9x9-TicTacToe](https://github.com/Devansu-Yadav/9x9-TicTacToe)

## Further Extension of the Project
Currently the game is built using the Pygame library of Python. What I am looking forward is to make a Web Application built on Django Framework and UI built using Html, CSS and using Javascript for detecting Cursor Movements and making it Interactive.   

## Languages
Currently it is using Python but the extension of the Project will also require use of Javascript.

**Comment by Souvikns** [comment]
@Devansu-Yadav your project Idea has been selected you can go ahead and make a pr adding your data in `src/data.json`.

**Comment by Devansu-Yadav** [comment]
Okay that's great! So i make a pr to Ninja-Developers Repo right?

**Comment by Souvikns** [comment]
This repo master branch

**Comment by Devansu-Yadav** [comment]
Okay.
